#!/usr/bin/env bash

if [[ $# -lt 1 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    echo "Usage: $0 <path-to-post>"
    exit 1
fi

title="$(./getPostTitle < "$1")"
postid="$(echo "$title" | ./getPostID)"
./unpublish "$postid"
